from dotenv import load_dotenv
from os import getenv
load_dotenv()


TOKEN = getenv("BOT_TOKEN")
# BOT_HOST_CONTAINER = getenv("BOT_HOST_CONTAINER")
# BOT_PORT_CONTAINER = getenv("BOT_PORT_CONTAINER")

FASTAPI_HOST_CONTAINER = getenv("FASTAPI_HOST_CONTAINER")
FASTAPI_PORT_CONTAINER = int(getenv("FASTAPI_PORT_CONTAINER"))

# BASE_URL_CONTAINER = f"http://{BOT_HOST_CONTAINER}:{BOT_PORT_CONTAINER}"

TELEGRAM_API = getenv("TELEGRAM_API")