services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    # volumes:
      # - ./database:/app
  
  bot:
    build:
      context: ./bot
    container_name: bot
    ports:
      - "8001:8001"
    env_file:
      - .env
  
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "8002:8002"
  
